server:
  port: ${APPLICATION_PORT:8080}

spring:
  application:
    name: transacao_api

# JPA
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

# Datasource - MySQL
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/transacao_api_db?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver

# Kafka
  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost:9092}
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: ${KAFKA_CONSUMER_GROUP_ID:transacao_api}
      auto-offset-reset: ${KAFKA_AUTO-OFFSET-RESET:latest}
    topic:
      transactions: transacoes
